FROM node:18-alpine

WORKDIR /app

RUN npm install -g json-server

COPY ./frontend/public/data.json /data/data.json

EXPOSE 3000

CMD ["json-server", "--host", "0.0.0.0", "--port", "3000", "--watch", "/data/data.json"]
