services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    ports:
      - "3000:3000"
